title: Ju Hang Sin
highlighter: rouge
safe: true
lsi: false
permalink: "/:title/"

kramdown:
    input: GFM
    hard_wrap: false

theme: jekyll-theme-slate

lsi: false

future: false

excerpt_separator: <!--more-->

include:
  - .well-known

