title: Ju Hang Sin
highlighter: rouge
safe: true
lsi: false
permalink: "/:title/"

google_analytics: UA-155003425-1

kramdown:
    input: GFM
    hard_wrap: false

theme: jekyll-theme-modernist

lsi: false

future: false

excerpt_separator: <!--more-->

include:
  - .well-known

